import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import StoreProvider from "@/components/StoreProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,session }) {
  return (
    <html lang="en">
      <body>
        <Provider >
        <StoreProvider>
      {children}
      </StoreProvider>
      </Provider>
        </body>
    </html>
  );
}
